# A neural network with a Perceptron
<br>

**Perceptron** - the foundation of a NN that 

- multiplies inputs by weights, adds bias, and feeds the result z to an activation function
- it's a NN with just one layer & a linear classifier with a binary output
- aka. linear binary classifier
- works best when linear seperability is given

Perceptron consists of: 
- input layer: different features/ inputs 
- weights and bias: features are weighted 
- weight sum: 
- activation function: 
  - it's deployed on each unit (neuron) of the NN, 
  - same AF in one shared layer
  - purpose of AF is to model complex non-linear phenomenon
  - types: linear, logistic sigmoid, treshold, ReLU, SoftMax
- linear separability: when data can be cleanly classified into one of two classes

In [2]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.linear_model import Perceptron

In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
standardize = StandardScaler()
standardized_X_test = standardize.fit_transform(X_test)
standardized_X_train = standardize.fit_transform(X_train)

In [8]:
standardized_X_test[0:10,]

array([[ 0.75315782,  0.6170992 ,  1.39875071,  1.83085937],
       [ 0.75315782, -1.66845339,  0.49511634,  0.28001379],
       [-0.43603874,  0.84565446, -1.14272097, -0.8831204 ],
       [-0.96457054, -2.35411917, -0.013178  , -0.10769761],
       [-0.83243759,  1.7598755 , -1.14272097, -1.01235753],
       [ 0.35675897, -0.75423236,  0.89045638,  0.66772518],
       [-1.75736824, -0.29712184, -1.19919812, -1.14159466],
       [-0.96457054, -0.06856658, -1.08624382, -1.14159466],
       [ 0.62102487,  0.84565446,  1.05988782,  1.5723851 ],
       [ 0.88529077, -0.5256771 ,  1.17284212,  1.44314797]])

In [9]:
# epochs/iterations=50
# eta0: Constant by which the updates are multiplied
# numpy.ravel() functions returns contiguous flattened array
# (1D array with all the input-array elements and with the same type as it)
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)
perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [10]:
y_pred = perceptron.predict(standardized_X_test)

In [11]:
print(y_test)

[2 1 0 1 0 1 0 0 2 2 1 1 2 1 0 1 2 2 0 0 2 1 0 1 0 0 0 1 2 0]


In [12]:
print(y_pred)

[2 1 0 1 0 2 0 0 2 2 1 1 2 1 0 1 2 2 0 0 2 1 0 1 0 0 0 1 2 0]


In [13]:
# check accuracy
# precision: correct predictions in all predictions
# recall: correctly recognized from all true values
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.90      0.95        10
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

